name: Code style

on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

jobs:
  format:
    runs-on: ubuntu-latest
    steps:
      - name: â˜ Checkout repository
        uses: actions/checkout@v3

      - name: ğŸ“œ Cache clang-format dependency
        uses: actions/cache@v3
        with:
          path: /usr/bin/clang-format
          key: ${{ runner.os }}-clang-format-${{ hashFiles('**/Makefile') }}
          restore-keys: |
            ${{ runner.os }}-clang-format-
      
      - name: ğŸ“¦ Install dependencies
        run: sudo apt-get install -y clang-format

      - name: ğŸ¨ Check code formatting
        run: make check-format

  lint:
    runs-on: ubuntu-latest
    steps:
      - name: â˜ Checkout repository
        uses: actions/checkout@v3

      - name: ğŸ“œ Cache clang-tidy dependency
        uses: actions/cache@v3
        with:
          path: /usr/bin/clang-tidy
          key: ${{ runner.os }}-clang-tidy-${{ hashFiles('**/Makefile') }}
          restore-keys: |
            ${{ runner.os }}-clang-tidy-
      
      - name: ğŸ“¦ Install dependencies
        run: sudo apt-get install -y clang-tidy

      - name: ğŸ§¹ Check code quality
        run: make lint
